// <auto-generated />
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20210201060521_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DataLayer.DTO.Artist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Metallica"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Led Zeppelin"
                        },
                        new
                        {
                            ID = 3,
                            Name = "ACDC"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Panthera"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Motorhead"
                        });
                });

            modelBuilder.Entity("DataLayer.DTO.Track", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ArtistID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ArtistID");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ArtistID = 1,
                            Name = "Master of Puppets"
                        },
                        new
                        {
                            ID = 2,
                            ArtistID = 2,
                            Name = "Satairway to Heaven"
                        },
                        new
                        {
                            ID = 3,
                            ArtistID = 3,
                            Name = "Back in Black"
                        },
                        new
                        {
                            ID = 4,
                            ArtistID = 4,
                            Name = "Walk"
                        },
                        new
                        {
                            ID = 5,
                            ArtistID = 5,
                            Name = "Ace of Spades"
                        });
                });

            modelBuilder.Entity("DataLayer.DTO.Track", b =>
                {
                    b.HasOne("DataLayer.DTO.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("DataLayer.DTO.Artist", b =>
                {
                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
